version: "3.8"

services:
  webapp:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    tty: true
    stdin_open: true
